name: Security Scan

on: push

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vulnerables/web-dvwa
          format: table
